spring:
  application:
    name: Rapido

  app:
    JWT_ACCESS_SECRET_KEY: mySecretKeyspkmndfsopkvajoirjgfpfngmoknmaccessToken
    JWT_REFRESH_SECRET_KEY: mySe12738aopsgjnspderewtekmndfsopkvajoirjg9438357437348763refreshToken
    jwtExpirationMs: 44000000
    jwtRefreshExpirationMs: 66000000


#  profiles:
#    active: dev  # Development Mode

#jdbc:mysql://localhost:3306/social_network?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/rapido_project
#    username: root
#    password: admin@123


  datasource:
      url: jdbc:mysql://mysql-2c64d766-mgiri2000mgiri-d1cb.l.aivencloud.com:21671/rapido_project?sslMode=REQUIRED&allowPublicKeyRetrieval=true
      username: avnadmin
      password: AVNS_tenhTP6S2wNg8aZLTMv
      driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update            #create
      show-sql: true
      format_sql: true
  show-sql: true
  open-in-view: true #false

  servlet:
    multipart:
      enabled: true  # Enable multipart uploads   #file-size-threshold: 2KB  # Threshold after which files are written to disk
      max-file-size: 100MB  # Max file size
      max-request-size: 100MB  # Total Max request size

  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 50
      shutdown:
        await-termination: true
        await-termination-period: 60s

#Email Credentials
  mail:
    host: smtp.gmail.com
    port: 587
    username: mahitosh.runtime@gmail.com
    password: zorfqhzdulxxtprs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

      domain_name: "Library"



#Swagger Ui
springdoc:
  swagger-ui:
    enabled: true  # Enable Swagger UI
    path: /swagger-ui.html  # URL path to access Swagger UI
  api-docs:
    enabled: true  # Enable API documentation
    path: /v3/api-docs  # Default path for OpenAPI JSON
  show-actuator: true  # (Optional) Show actuator endpoints in Swagger
#  packages-to-scan: com.yourpackage.controller  # (Optional) Restrict to specific package
#  paths-to-match: "/api/**"  # (Optional) Define API paths to include in documentation

#Cloudnary Key
cloudinary:
  cloud_name: dvxef5plb
  api_key: 272592496495854
  api_secret: KiAp22_2sT7GZ2AqZHcQEYkTZjE

otp:
  api-key: 0fef925f-30a5-11f0-8b17-0200cd936042
  template: LOGIN_OTP


#Log Files
#logging:
#  level:
#    root: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.engine.internal.Cascade: TRACE  # Use for check any on Cascade of entity
#    org.type.descriptor: DEBUG
#    org.springframework.web: DEBUG  #INFO
#    org.springframework.transaction: DEBUG   # Use for check any on transition
#    org.springframework.orm.jpa.JpaTransactionManager: DEBUG # Use for check any on transition
#    com.example.librarymanagement:
#    # Debug multipart processing
#    org.apache.tomcat: DEBUG
#  file:
#    name: logs/application.log

#logging:
#  host: localhost       # Use localhost for local dev, change to 'logstash' in production (Docker)
#  port: 5000
#  level:
#    root: info
#    com.maven.Rapido: trace


# File Storage Properties
file:
  upload-dir: ./uploads

# Actuator Properties
management:
  endpoints:
    web:
      exposure:
        include: "*"


#URL
FRONTEND_URL: "https://rapido-project-spring-boot.onrender.com,http://localhost:5173"
FORGET_PASSWORD_URL: "http://localhost:4200"

#Server
server:
  port: 5001

  # Error Handling
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
    include-exception: true

google:
  api:
    key: AIzaSyAfiISUmg_6Bdcw0XI4GhocAi76a9_sYY8

#Aiuvn
#redis:
#  host: valkey-2ef72db6-mgiri2000mgiri-d1cb.l.aivencloud.com
#  port: 21672
#  password: AVNS_zpvo8pRRYXshBM2XTiR

redis:
  host: gusc1-evolved-cod-31734.upstash.io
  port: 31734
  password: 4ac4dd4be6444445908c6a96593e695a


# Enable WebSocket debugging
logging:
  level:
     org.springframework.web.socket: DEBUG
     org.springframework.messaging: DEBUG

razorpay:
  key: "rzp_test_9b1c2f3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t"
  secret: "rzp_test_9b1c2f3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t_secret"

storage:
  s3:
    endpoint: "https://s3.us-west-004.backblazeb2.com"
    access-key: AKIA47GB7XMCSTJOQR6H
    secret-key: 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
    region: ap-south-1
    bucket-name: uatinvespy


app:
  firebase-configuration-file: classpath:fcmnotification-14-firebase-adminsdk-yzh8u-5ac73ffbd5.json

